### ISSUE TITLE
Check lldp napp

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-napps#157]
To run a ping in mininet, I had to make several changes to the lldp napp. I'm wondering if there's something wrong there. I'm checking for many None or empty strings/bytes as seen in https://github.com/kytos/kyco-core-napps/commit/d41909a4e1dbb21f5f6fedbe3498806da1334efc.

**Comment by macartur** [comment]
Using the unpack_non_empty we can find a string and int but the expected to data.value is bytes

**Comment by macartur** [comment]
This was fixed in kytos/python-openflow#253 .

**Comment by macartur** [comment]
There are another error in of_lldp, I am verifying.

**Comment by macartur** [comment]
It's working in the last version of python3-openflow.
