### ISSUE TITLE
Enable Scrutinizer

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-napps#159]
Support for Tavis and coveralls were added in PR #158. The services must only be enabled by a Kytos admin.

**Comment by diraol** [comment]
@cemsbr and @beraldoleal are we going to use scrutinizer on this repo too? If so, I think that this issue can be closed in favor of another one to setup scrutinizer here, right?

**Comment by beraldoleal** [comment]
@diraol Yes. We are still testing Scrutinizer. But yes, probably this will be scrutinizer too.

**Comment by cemsbr** [comment]
I have a branch with scrutinizer setup, but we need the tests to pass to make sure it is working. The code is broken because of #197.
