### ISSUE TITLE
long_description kytos.json attribute

### ISSUE THREAD

**Issue by diraol** [kytos/kytos-napps#164]
Should we remove this attribute from `kytos.json`, since we already have the 'description' field and also the "README.rst" file?

I stand for this idea of removing the long_description attribute.

**Comment by cemsbr** [comment]
Just to clarify: we have `description` meaning short description, `long_description` and the README.rst.

Where is long_description currently used?

**Comment by beraldoleal** [comment]
I agree. Let's keep description "for short description" and README.rst.
