### ISSUE TITLE
Just one FeatureRequest per switch

### ISSUE THREAD

**Issue by jab1982** [kytos/kytos-napps#166]
By default, the OpenFlow controller should send a FeatureRequest only after the first Hello. The of_core is sending a FeatureRequest message every time there is a Hello or a EchoReply message.

of_core:177
```    
    @listen_to('kytos/of.core.messages.out.ofpt_hello',
               'kytos/of.core.messages.out.ofpt_echo_reply')
    def send_features_request(self, event):
```

**Comment by beraldoleal** [comment]
@diraol I think that we discussed this after the workshop. If I remember right, some of our cases needs this. So I suggest to implement as config parameter in settings with default to false.

**Comment by diraol** [comment]
@beraldoleal yes, we can a specific 'settings' attribute to deal with this.

**Comment by beraldoleal** [comment]
@erickvermot fixed this, but since that there is need for more tests, I'm moving this to 2017.1b2.

**Comment by erickvermot** [comment]
@macartur, since my setup still has some issues, could you test this commit for me please?
I think now this is more important than to try to replicate the problems I'm having with mininet..
Thanks a lot!
