### ISSUE TITLE
Review all events names

### ISSUE THREAD

**Issue by diraol** [kytos/kytos-napps#168]
Previously we were using dot `.` on the napps names. Since we changed the names to forbid dots and replaced them with underscore, we need to update the events names too.

On the future this part of the event name will be automatically added by the method responsible for adding events on the buffers.

**Comment by cemsbr** [comment]
Also, there are events like `kytos/core.connection`... I believe it should be `kytos/of_core.connection`.

**Comment by diraol** [comment]
Actually the event is `kyco/core.connection.new` and it is generated on the `tcp_server` kyco core module . =)
