### ISSUE TITLE
In l2ls app, "App information goes to app_name.json"

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-napps#19]
This was a TODO in setup method. It had `self.name = 'kytos.l2_learning_switch'`. I noticed there is a kytos.json file with `"name" = "of.l2ls"` and that's why I removed both TODO and `self.name` line, but I'm not sure whether there is anything else to do (e.g., change `kytos.json` to `app_name.json` as said in TODO). Could the TODO creator check if this is solved?

**Comment by diraol** [comment]
The ``TODO`` was added prior to the definition of the json file. It will be ``kytos.json``.

But, at least until now, we are not parsing the json file, so the napp will not have the 'name' attribute when loaded by the controller. That is not a problem if we are not using the napp name anywhere - I'm not sure about it.

**Comment by cemsbr** [comment]
In the logs, napp names are like "Thread-1122". We could get the name from kytos.json.

**Comment by beraldoleal** [comment]
Agreed @cemsbr . Should be `author/napp_name`

**Comment by macartur** [comment]
After to close the #99, each Napp now read the kytos.json and updates yours object attributes. In the logs, the napp name of each thread is `author/napp_name`.

**Comment by cemsbr** [comment]
Indeed, this was fixed by kytos/kytos#287.
