### ISSUE TITLE
update requirements.txt

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos-napps#193]
- include comment for python3.6 requirement
- include comment for setuptools requirement
- include comment for pip requirement
- include comment to show pip rrdtools depends on rrdtools lib previously installed

**Comment by diraol** [comment]
`pip` is not a requirement anymore. =)

@erickvermot did you mean "_include comment to show that `python-rrdtools` depends on rrdtools lib previously installed_" on the fourth item?

**Comment by erickvermot** [comment]
requirements.txt is listing [``rrdtool``](https://pypi.python.org/pypi/rrdtool/0.1.11) and not [``python-rrdtool``](https://pypi.python.org/pypi/python-rrdtool/1.4.7).

**Comment by diraol** [comment]
@erickvermot That is correct, since there is no `python-rrdtool` package on `Pypi`.

**Comment by cemsbr** [comment]
Let's keep in mind we don't run this project, but install them as Kytos NApps using kytos-utils. Thus, this repo is for developers and we don't need to be extra careful explaining the requirements.

The _rrdtool_ dependency is in the _of_stats_ README, including the required packages to build it. I believe we can close this for now and focus in each NApp documentation assuming the user had already installed Kytos (with Python 3.6, pip, etc).
