### ISSUE TITLE
l2ls does not handle correctly no_match packet-ins

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos-napps#221]
When running kytos with of_core and of_l2ls, the first two pings between the hosts are dropped. this happens because of_l2ls (when the switch port is known) sends the flow_mod, but does not handle (pass-on) the packet_in, dropping it silently.

**Comment by diraol** [comment]
@erickvermot #222 fixes this issue? If so, do not forget to add the "fix <issue_number>" (or fixes, close, closes, etc) on the commit message next time.

**Comment by erickvermot** [comment]
yes, sorry I forgot.
