### ISSUE TITLE
looks like of_stats won't shut down

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos-napps#225]
When shutting down kytos, sometimes it freezes at the of_stats shutdown:
```
2017-05-10 09:03:31,242 - INFO [kytos.core.controller] (MainThread) Shutting down NApp kytos/of_stats...
```

**Comment by erickvermot** [comment]
I think it is important to mention that it could be related to my disk being full (ref: https://github.com/kytos/kytos-napps/issues/224).
I was experiencing this at the same time.

**Comment by cemsbr** [comment]
I believe this is due to the disk being full. I added instructions on how to delete the database in the troubleshooting sections of the of_stats readme. Re-open if you still experience problems.
