### ISSUE TITLE
[of_flow_manager]  insert_flow needs refactoring

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-napps#238]
The method expects to have a JSON object as data, but passes the wrong value while creating the new flow using `from_dict`, leading to an exception. Also, it can be simplified to let data forms to be posted instead of JSON: it becomes easier for the API user and we can handle the data internally.

**Comment by renanrodrigo** [comment]
As seen later, the problem is not the `from_dict` method but the format requirements for a JSON entry to create a flow. The format needs to be simpler and intuitive. We need proper documentation also, as noted in #237.

**Comment by beraldoleal** [comment]
@renanrodrigo Two things here again. Let's split this issue.

Also, json vs form needs to be discussed.
