### ISSUE TITLE
Inconsistency in switch identification on the console

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-napps#265]
When an OpenFlow 1.0 handshake is done, the switch is identified at the console by its DPID. However, after an OpenFlow 1.3 handshake, the switch is identified by an integer.

As seen in the `kytos` console:
OpenFlow 1.0:
`2017-06-26 15:24:36,714 - INFO [kytos/of_core] (Thread-159) Connection ('127.0.0.1', 53318), Switch 00:00:00:00:00:00:00:01: OPENFLOW HANDSHAKE COMPLETE`

OpenFlow 1.3:
`2017-06-26 15:25:28,707 - INFO [kytos/of_core] (Thread-402) Connection ('127.0.0.1', 53330), Switch 1: OPENFLOW HANDSHAKE COMPLETE`

**Comment by erickvermot** [comment]
I don't think it is minor since it is an important part of the handshake, and of the switch identification.
Thanks for noticing @renanrodrigo.
