### ISSUE TITLE
ImportError: cannot import name 'rest'

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/kytos-napps#291]
```
File "/projects/env_kytos/var/lib/kytos/napps/kytos/of_flow_manager/main.py", line 6, in <module>
    from kytos.core import KytosEvent, KytosNApp, log, rest
ImportError: cannot import name 'rest'
```
I have just pushed everything from kytos repository.
Has the "rest" changed to kytos.core.napps?

**Comment by cemsbr** [comment]
`rest` is in both `kytos.core` and `kytos.core.napps`. Make sure you have installed the latest kytos. Try `pip install -r requirements/dev.txt` in kytos folder with the latest master branch code.

**Comment by rmotitsuki** [comment]
Thanks @cemsbr.
It really seems something in my environment.
